Formula/nginx-full.rb
Formula/websockify-nginx-module.rb

Version 0.0.2 of websockify-nginx-module
The nginx-full formula has been modified to make use of it.
Compiled and tested locally.
Please note that websockify is not the same thing as nginx's existing WebSocket proxying; instead, it is a WebSocket - TCP gateway.

New formula websockify-nginx-module: 0.0.2

---

Formula/nginx-full.rb
Formula/tcp-proxy-nginx-module.rb

And now installs correctly; patch moved to
nginx-full.

tcp-proxy-nginx-module: Updated to 0.4.5

---

Formula/nginx-full.rb
Formula/small-light-nginx-module.rb

To support GD, Imlib2 or both libs, use --with-gd / --with-imlib2 options on installing small-light-nginx-module directory.

add support to compile with ngx_small_light module #49

---

Formula/openresty.rb

Without this dependency, I was getting the following build error:
```
checking for OpenSSL library ... not found
checking for OpenSSL library in /usr/local/ ... not found
checking for OpenSSL library in /usr/pkg/ ... not found
checking for OpenSSL library in /opt/local/ ... not found
./configure: error: SSL modules require the OpenSSL library.
You can either do not enable the modules, or install the OpenSSL library
into the system, or build the OpenSSL library statically from the source
with nginx by using --with-openssl=<path> option.
```

Add openresty dependency on openssl

---

Formula/nginx-full.rb

Hi, I'm ngx_mruby author.
`make build_mruby generate_gems_config` occur compile error because this command can't create mrbgems flags file correctly.
ref: https://github.com/matsumoto-r/ngx_mruby/wiki/Install#or-configure-with---add-modulengx_mruby_src-for-nginx-and-make-it

Fix build process of ngx_mruby

---

Formula/mruby-nginx-module.rb
Formula/nginx-full.rb

Currently, ngx_mruby doesn't work completely unless you also add `--with-set-misc-module` to the build in order to get the `ngx-devel-kit` module added. 
This adds a dependency for `ngx-devel-kit` to the mruby module and ensures the `--add-module` line is also included when building with mruby.

Make ngx-devel-kit a dependency for mruby

---

Formula/lua-nginx-module.rb

bugfix: fixed compilation errors with nginx 1.9.11+.
Thanks Charles R. Portwood II and Tomas Kvasnicka for the report in openresty/lua-nginx-module#669 and openresty/lua-nginx-module#668, respectively.
https://github.com/openresty/lua-nginx-module/compare/v0.10.1rc0...01727a3

lua-nginx-module 0.10.1rc0 (nginx 1.9.11+)

---

Formula/nginx-full.rb
Formula/openresty.rb

http_slice has been available from 1.9.8 - expose it in options.

expose http_slice_module in openresty and nginx-full

---

Formula/nginx-full.rb

These modules depend on ngx-devel-kit, but don't trigger its inclusion. It
would be nice to have a way to detect this automatically, or have modules set
this flag, instead of needing to keep track in two different places.
Fixes #210.

Build ngx-devel-kit when compiling array-var or lua modules

---

Formula/naxsi-nginx-module.rb

added `version_scheme 1` so that an upgrade from 0.55rc2 -> 0.55 will be
triggered. brew currently thinks 0.55rc2 is version "2". An explicit
`version "0.55rc2"` or `version "0.55-rc2"` should have been used, but
it's too late now.

naxsi-nginx-module 0.55

---

Formula/openresty.rb

but offer a way to turn it off by `--without-ipv6`.
some directives like `resolver ... ipv6=off;` work only with ipv6 support compiled in.
That makes some configurations incompatible without ipv6 support.

[openresty] compile with ipv6 by default

---

CONTRIBUTING.md

Fix broken link to Homebrew standards in CONTRIBUTING.md.

Update link to Homebrew standards in CONTRIBUTING.md

---

Formula/openresty-debug.rb
Formula/openresty-openssl.rb
Formula/openresty.rb

- use `openresty-openssl` instead of `openssl`  to enable those advanced features like `ssl_session_fetch_by_lua*` and `ssl_session_store_by_lua*`.
- use the same configure args as [`rpm` package](https://github.com/openresty/openresty-packaging/blob/master/rpm/SPECS/openresty.spec) 
- add `skip_clean` for `opm` running as normal

openresty: bundle openssl and debug formula

---

Formula/openresty-openssl.rb

follow the rpm package upgrade: https://github.com/openresty/openresty-packaging/commit/618f233fd2feff294eb2ae1669f7b57060a6af6f

OpenResty: upgraded OpenSSL to 1.0.2k.

---

Formula/nginx-full.rb

```
Changes with nginx 1.13.0                                        25 Apr 2017
*) Change: SSL renegotiation is now allowed on backend connections.
*) Feature: the "rcvbuf" and "sndbuf" parameters of the "listen"
directives of the mail proxy and stream modules.
*) Feature: the "return" and "error_page" directives can now be used to
return 308 redirections.
Thanks to Simon Leblanc.
*) Feature: the "TLSv1.3" parameter of the "ssl_protocols" directive.
*) Feature: when logging signals nginx now logs PID of the process which
sent the signal.
*) Bugfix: in memory allocation error handling.
*) Bugfix: if a server in the stream module listened on a wildcard
address, the source address of a response UDP datagram could differ
from the original datagram destination address.
```

nginx 1.13.0 (mainline/devel)

---

Formula/nginx-full.rb

Avoid link error to specify `-lcrypto` expricitlly by using `NGX_MRUBY_LDFLAGS` supported at [ngx_mruby v1.20.1](https://github.com/matsumotory/ngx_mruby/releases/tag/v1.20.1).
`The no-sandbox option doesn't work for me.` at https://github.com/Homebrew/homebrew-nginx/issues/312 will be fixed.
~~- [ ] Written a sensible test? (The best test is to compile and run a sample program.)~~
~~- [ ] Removed the `revision` line, if any, when bumping the version number?~~
~~- [ ] Added/bumped the `revision` number if the changes affect the precompiled bottles?~~

Fix mrbgems link error

---

Formula/nginx-full.rb
Formula/tarantool-nginx-module.rb

There's the problem - no tests in module, since sane test needs started tarantool instance.

tarantool-nginx-module 2.5 (new formula)

---

Formula/openresty-debug.rb
Formula/openresty.rb

follow the new version of OpenResty : [https://openresty.org/en/changelog-1013006.html](https://openresty.org/en/changelog-1013006.html)

upgraded OpenResty to 1.13.6.1

---

Formula/rtmp-nginx-module.rb

I suppose it should prevent from getting next error:
Error: SHA256 mismatch
Expected: 621d406f20195400603f492ec785ea1c01af04e877bc84c1aeb40487d27dcc13
Actual: 11991a7bedfb978813ef9f75cd05f8a2d74caed52d89683f8cdecce5515108cf
Archive: /Users/ivan/Library/Caches/Homebrew/rtmp-nginx-module--patch-621d406f20195400603f492ec785ea1c01af04e877bc84c1aeb40487d27dcc13.diff
To retry an incomplete download, remove the file above.

Fix SHA256 to actual value; Increment revision;

---

Formula/mod-zip-nginx-module.rb

Updated to nginx-mod_zip, released 8 Oct 2017. 
Builds fine with nginx/1.12.2 on High Sierra 10.13.6.

Updated to latest version of nginx-mod_zip

---

Formula/openresty.rb

Brew will stop installation due to ambiguous references. This fixed it for me.

Make references to openresty-ssl explicit

---

Formula/lua-nginx-module.rb

Fixes a segfault when trying to use init_worker_by_lua in newer versions
of nginx.
I did not update to 0.10.15 since that now requires resty.core as a
dependency.
References:
- https://github.com/openresty/lua-nginx-module/issues/1348
- https://github.com/openresty/lua-nginx-module/pull/1352
- https://github.com/openresty/lua-nginx-module/pull/1349
```
wbond/nginx/lua-nginx-module:
* C: 1: col 1: A `test do` test block should be added
Error: 1 problem in 1 formula detected
```
*There doesn't appear to be a `revision` in lua-nginx-module.*
*There doesn't appear to be a `revision` in lua-nginx-module.*
*There don't appear to be any existing tests. I did, however, tap my fork and install nginx with the lua module and successfully run the configuration that uses `init_worker_by_lua` and nginx …

lua-nginx-module 0.10.14

---

Formula/nginx-full.rb
Formula/njs-nginx-module.rb

This PR introduces support for the [njs module](https://nginx.org/en/docs/njs). This is my first time messing with Homebrew, and I used it on Fedora inside of a container...but it should still work. I intend on shipping it to developers on my team to easily enable this module on MacOS; so if anything doesn't work as expected this PR (or a subsequent PR) will address it.

Add module: njs 0.3.9

---

Formula/rtmp-nginx-module.rb

I use that on an Apple Silicon mac, since there're no more patches needed it closes issue #382

upgrade rtmp module to v1.2.2-r1 no patch needed

---

Formula/nginx-full.rb

This resolves #420  by supplying a modern service definition equivalent to the launchd `plist` previously supplied.
Tests not examined; I had a number of issues installing a few of my desired modules which were difficult to pin down, or I just disabled that option and moved on…

Replace modern service definition.

---

Formula/nginx_upstream_check_module.rb

…hcheck_nginx_upstreams
- add a new module, nginx_upstream_check_module to replace healthcheck-nginx-module. cuz healthcheck-nginx-module is not maintained by the owner any more.
- It can resolve the issue #263 by using new module.

✨ feat: add nginx_upstream_check_module to replace the previous health check module

---

Formula/nginx-full.rb
Formula/nginx-upstream-check-module.rb
Formula/nginx_upstream_check_module.rb

- format the name from nginx_upstream_check_module  to nginx-upstream-check-module to keep the same style
- add the new module defined in nginx-full.rb, mentioned under the comment of #425

feat: format the name and support it in nginx-full
