- Formula/ajp-nginx-module.rb
- Formula/nginx-full.rb
Added support to nginx_ajp_module. My first homebrew-pr, so just decline if this is not correctly done :smile:.
> add support to compile with ajp-nginx-module

- .travis.yml
- Formula/nginx-full.rb
- Formula/nginx-xsltproc-module.rb
- Formula/xsltproc-nginx-module.rb
Hello,
I would like to add XSLT proc module written by my friend - yoreek.
Here is the link to his repo:
https://github.com/yoreek/nginx-xsltproc-module
> Add XSLT proc module

- Formula/small-light-nginx-module.rb
ngx_small_light module has been updated to v0.6.7.
> update ngx_small_light to v0.6.7

- Formula/nginx-full.rb
- load configuration put in etc/servers.
- Takes advantage of upstream landing LibreSSL support.
- Refactors the args list.
Homebrew/homebrew#38729
Homebrew/homebrew#38901
> Sync homebrew/nginx

- Formula/small-light-nginx-module.rb
ngx_small_light is updated to v0.6.11.
> small-light-module 0.6.11

- Formula/http-accounting-nginx-module.rb
- Formula/nginx-full.rb
> ngx_http_accounting_module 
Homebrew/homebrew-nginx#49 @Mirocow
> http-accounting-nginx-module 0.5

- Formula/naxsi-nginx-module.rb
- Formula/nginx-full.rb
Hi, lately I've been using Naxsi locally with learning mode on to build up my core rules for use in production. Thought it might be useful to have this in the repository. Just uses the simple `--with-naxsi-module` syntax to install.
> Add naxsi module formula

- Formula/lua-nginx-module.rb
Changelog: https://github.com/openresty/lua-nginx-module/compare/v0.9.16...v0.9.19
> lua-nginx-module 0.9.19

- Formula/small-light-nginx-module.rb
ngx_small_light is updated to v0.6.12.
> small-light-module 0.6.12

- Formula/small-light-nginx-module.rb
ngx_small_light is updated to v0.6.13.
> small-light-module 0.6.13

- Formula/geoip2-nginx-module.rb
- Formula/nginx-full.rb
Add 3rd party [geoip2 module](https://github.com/leev/ngx_http_geoip2_module)
> Add geoip2 module

- Formula/auth-ldap-nginx-module.rb
Cherry merge kvspb/nginx-auth-ldap@d0f2f82
* kvspb/nginx-auth-ldap#89
* kvspb/nginx-auth-ldap#95
* kvspb/nginx-auth-ldap#100
* kvspb/nginx-auth-ldap#109
> nginx-auth-ldap: kvspb/nginx-auth-ldap@d0f2f82

- Formula/small-light-nginx-module.rb
ngx_small_light is updated to v0.6.14.
> small-light-module 0.6.14

- Formula/mruby-nginx-module.rb
- Formula/nginx-full.rb
> mruby-nginx-module 1.16.0

- Formula/small-light-nginx-module.rb
ngx_small_light is updated to v0.6.15.
> small-light-module 0.6.15

- Formula/naxsi-nginx-module.rb
* Added support for RAW_BODY (rules to be matched against the full, raw body. Can be useful to match rules against unparsed content : XML, serialized java objects etc.)
* Confirmed support as a dynamic module (introduced in nginx 1.9.11)
* Better makefile for testing & dev, increased coverage
* Minor bug-fixes (nbs-system/naxsi#120, nbs-system/naxsi#241, nbs-system/naxsi#217, nbs-system/naxsi#231)
> naxsi-nginx-module 0.55rc1

- Formula/small-light-nginx-module.rb
ngx_small_light is updated to v0.7.3.
> small-light-module 0.7.3

- Formula/nginx-full.rb
> nginx 1.11.5 (devel)

- Formula/nginx-full.rb
Bump nginx-full to latest stable nginx release
> nginx 1.10.2

- Formula/nchan-nginx-module.rb
sorry, i left an important fix out of the version from earlier today
> nchan 1.0.6

- Formula/nchan-nginx-module.rb
> nchan 1.0.7

- Formula/openresty.rb
update openresty to 1.11.2.2 and formula description
> openresty 1.11.2.2, update description

- Formula/nginx-full.rb
> nginx 1.11.9 (devel)

- Formula/nginx-full.rb
> mail-ssl, stream-ssl, stream-ssl-preread

- Formula/nchan-nginx-module.rb
Sorry, I messed up the version commit. This is the correct hash for the release.
> nchan 1.1.2

- Formula/nginx-full.rb
Fixes #271
Don't know where @denji got the incorrect checksum from.
> Fix checksum for nginx-1.11.12.tar.gz

- Formula/nginx-full.rb
> nginx 1.12.0 (stable)

- Formula/rtmp-nginx-module.rb
* sergey-dryabzhinsky/nginx-rtmp-module#234 (https://github.com/Homebrew/homebrew-nginx/issues/263#issuecomment-294285729)
* https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/compare/v1.1.7.10...542106e
> nginx-rtmp-module: 1.1.7.11-dev

- Formula/openresty-debug.rb
- Formula/openresty-openssl.rb
- Formula/openresty.rb
follow the new version of OpenResty : https://openresty.org/en/changelog-1011002.html
> upgraded OpenResty to 1.11.2.3.

- Formula/openresty-openssl.rb
> openresty-openssl: keg_only

- Formula/lua-nginx-module.rb
Fixes https://github.com/Homebrew/homebrew-nginx/issues/299.
> lua-nginx-module: fix patch checksum

- Formula/openresty.rb
> upgrade to version 1.11.2.5

- Formula/nginx-full.rb
> nginx 1.12.2

- Formula/nchan-nginx-module.rb
backwards-compatibility update
> nchan 1.1.13

- Formula/auth-digest-nginx-module.rb
> auth-digest-nginx-module: 0.2

- Formula/nchan-nginx-module.rb
> nchan 1.2.0

- Formula/upload-nginx-module.rb
Nginx Upload Module with http2 support.
> Latest Upload Module 57bbb0d as of March 18, 2018.

- README.md
Old link to additional modules was broken. Updated to correct link.
> Update link to addition modules in README.md

- Formula/vod-nginx-module.rb
> vod-nginx-module 1.24

- Formula/lua-nginx-module.rb
- Formula/nginx-full.rb
adapt to Apple silicon brew path
use luajit 2.1
Fixes issues #409 and #407
> lua-nginx-module v0.10.22: Apple Silicon & luajit 2.1
